######################################################################
# Automatically generated by qmake (3.0) Thu May 30 17:29:01 2019
######################################################################

TEMPLATE = app
TARGET = PIL
INCLUDEPATH += .

# Input
HEADERS += pil.h
SOURCES += main.cpp pil.cpp


QT += core gui widgets

QMAKE_CXXFLAGS = -std=c++11
QMAKE=LFLAGS = -std=c++11

QT += testlib