######################################################################
# Automatically generated by qmake (3.0) Thu May 30 17:26:40 2019
######################################################################

TEMPLATE = app
TARGET = NET
INCLUDEPATH += .

# Input
HEADERS += lamportclock.h net.h vectorclock.h
SOURCES += lamportclock.cpp main.cpp net.cpp vectorclock.cpp

QT += core gui widgets

QMAKE_CXXFLAGS = -std=c++11
QMAKE=LFLAGS = -std=c++11

QT += testlib
